# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: maven
    directory: "/RemoteSpiNNaker"
    schedule:
      interval: "weekly"
    labels:
      - "bug"
      - "dependabot"
    milestone: 7   # This is the *ID* for the 7.0.0 milestone
    assignees:
      - "rowleya"
    reviewers:
      - "dkfellows"
  - package-ecosystem: maven
    directory: "/RemoteSpiNNaker"
    schedule:
      interval: "weekly"
    target-branch: "java-11"
    labels:
      - "bug"
      - "dependabot"
    milestone: 7   # This is the *ID* for the 7.0.0 milestone
    assignees:
      - "rowleya"
    reviewers:
      - "dkfellows"
      