language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Look for POM in subfolder
  - cd RemoteSpiNNaker
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dmaven.compiler.showDeprecation=true
script:
  - mvn test -B -Dmaven.javadoc.skip=true
  ############################################
  ### STYLE ENFORCEMENT CURRENTLY DISABLED ###
  ############################################
  ### Much work required to fix the code   ###
  ### style before this can be turned on   ###
  ### on a main branch.                    ###
  ############################################
  # - mvn checkstyle:check -Dmaven.javadoc.skip=true
  - mvn javadoc:javadoc
