language: java
jdk: oraclejdk8
before_install:
  - cd RemoteSpiNNaker
  - mvn dependency:resolve
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B -Dmaven.javadoc.skip=true
  - mvn checkstyle:check -Dmaven.javadoc.skip=true
  - mvn javadoc:javadoc
