language: java
os: linux
dist: focal
jdk:
  - openjdk11
  - openjdk8
cache:
  directories:
    - $HOME/.m2

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - unset _JAVA_OPTIONS
  - cfg=$PWD/.travis/travis-settings.xml
  # Look for POM in subfolder
  - cd RemoteSpiNNaker

install:
  # Not a critical failure for this to fail
  - mvn -B dependency:resolve dependency:resolve-plugins --settings $cfg || true

script:
  - mvn apache-rat:check     --settings $cfg -V || (find . -type f -name 'rat*.txt' -print | xargs grep -l unapproved | xargs cat; exit 1)
  - mvn install              --settings $cfg -Dmaven.javadoc.skip=true -DskipTests=true
  - mvn verify jacoco:report --settings $cfg -Dmaven.javadoc.skip=true
  - mvn checkstyle:check     --settings $cfg -Dmaven.javadoc.skip=true
  - mvn javadoc:aggregate    --settings $cfg

after_success:
  - mvn coveralls:report     --settings $cfg
