language: java
jdk:
  - oraclejdk8
  - openjdk11
cache:
  directories:
    - $HOME/.m2

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - unset _JAVA_OPTIONS
  # Look for POM in subfolder
  - cd RemoteSpiNNaker

install:
  # Not a critical failure for this to fail
  - mvn -B dependency:resolve dependency:resolve-plugins --settings ../.travis/travis-settings.xml || true

script:
  - mvn apache-rat:check --settings ../.travis/travis-settings.xml -V || (find . -type f -name 'rat*.txt' -print | xargs grep -l unapproved | xargs cat; exit 1)
  - mvn install --settings ../.travis/travis-settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
  - mvn verify --settings ../.travis/travis-settings.xml -Dmaven.javadoc.skip=true jacoco:report
  - mvn checkstyle:check --settings ../.travis/travis-settings.xml -Dmaven.javadoc.skip=true
  - mvn javadoc:aggregate --settings ../.travis/travis-settings.xml

after_success:
  - mvn coveralls:report --settings ../.travis/travis-settings.xml
