language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - cd RemoteSpiNNaker
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B -Dmaven.javadoc.skip=true
  - mvn checkstyle:check -Dmaven.javadoc.skip=true
  - mvn javadoc:javadoc
