# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Test
on: [push]
env:
  CI_NAME: "Github Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [11, 14, 17]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set dynamic information
      env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
      run: |
        echo "CI_BRANCH=${BRANCH_NAME_OR_REF#refs/heads/}" >> $GITHUB_ENV
        echo "CI_PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
        echo "SETTINGS_FILE=$PWD/.github/settings.xml" >> $GITHUB_ENV
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Maven library-update
      # This step may fail; it isn't a problem (it exists to stabilize the next step)
      run: mvn -B dependency:resolve dependency:resolve-plugins --settings $SETTINGS_FILE || true
      working-directory: RemoteSpiNNaker
      continue-on-error: true

    - name: Maven compile
      run: mvn install --settings $SETTINGS_FILE -DskipTests=true -Dmaven.javadoc.skip=true
      working-directory: RemoteSpiNNaker
    - name: Maven test
      id: test
      run: mvn verify --settings $SETTINGS_FILE -Dmaven.javadoc.skip=true jacoco:report
      working-directory: RemoteSpiNNaker
    - name: "Report: Coverage via coveralls.io"
      run: |
        mvn coveralls:report --settings $SETTINGS_FILE --no-transfer-progress -DrepoToken=$COVERALLS_SECRET
      env:
        CI_NAME: github
        CI_BUILD_NUMBER: ${{ github.run_id }}
        CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
        COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
      working-directory: RemoteSpiNNaker
      continue-on-error: true

    - name: "Post-Run: Purge SNAPSHOTs"
      # Do not cache SNAPSHOT dependencies; we don't use external snapshots
      # and we will always rebuild internal snapshots.
      run: mvn dependency:purge-local-repository --settings $SETTINGS_FILE -DsnapshotsOnly=true -DreResolve=false
      working-directory: RemoteSpiNNaker
      continue-on-error: true

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set dynamic information
      run: |
        echo "SETTINGS_FILE=$PWD/.github/settings.xml" >> $GITHUB_ENV
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Maven library-update
      # This step may fail; it isn't a problem (it exists to stabilize the next step)
      run: mvn -B dependency:resolve dependency:resolve-plugins --settings $SETTINGS_FILE || true
      working-directory: RemoteSpiNNaker
      continue-on-error: true

    - name: Maven rat
      run: mvn apache-rat:check --settings $SETTINGS_FILE -V || (find . -type f -name 'rat*.txt' -print | xargs grep -l unapproved | xargs cat; exit 1)
      working-directory: RemoteSpiNNaker
    - name: Maven compile
      run: mvn install --settings $SETTINGS_FILE -DskipTests=true -Dmaven.javadoc.skip=true
      working-directory: RemoteSpiNNaker
    - name: Maven checkstyle
      run: mvn checkstyle:check --settings $SETTINGS_FILE -Dmaven.javadoc.skip=true
      working-directory: RemoteSpiNNaker
    - name: Maven javadoc
      run: mvn javadoc:aggregate --settings $SETTINGS_FILE
      working-directory: RemoteSpiNNaker

    - name: Validate CITATION.cff
      uses: dieghernan/cff-validator@main

    - name: "Post-Run: Purge SNAPSHOTs"
      # Do not cache SNAPSHOT dependencies; we don't use external snapshots
      # and we will always rebuild internal snapshots.
      run: mvn dependency:purge-local-repository --settings $SETTINGS_FILE -DsnapshotsOnly=true -DreResolve=false
      working-directory: RemoteSpiNNaker
      continue-on-error: true
